### PR TITLE
Migrate to V2 of the unthink stack

### PR DESCRIPTION
**Pull request by tommyphilyaw**
This PR serves as the migration of the stack from V1 to V2 and will track progress to a stable V2.

### CODE REVIEW

**Comment by tommyphilyaw** [comment]
Closing this PR in preference of #35 - the feature branch will hang around shortly to ensure I have everything ported to the packages.

**Comment by tommyphilyaw** [comment]
Ha. Closed wrong PR.

**Comment by tommyphilyaw** [comment]
@lxndrdagreat This should just work when you pull it down. Ported the hello world resource and version resource over. 

The two packages this depends have also been pushed to NPM as "beta" packages and this project is pulling them in via NPM vs the old stack which was using specific git commits for the unthink layer.

As noted in my commit message I have stripped out:
- MongoDb
- Inversify
- The base resource (don't need it)
- The error model we had in there - the new foundation layer includes a default error that is in parity with the one removed.

I wanted to "reset" the project and add these things back in within the context of V2 where applicable vs blindly porting them.

**Comment by tommyphilyaw** [comment]
@lxndrdagreat One step closer. Nothing changed in stack, but the dependent foundation packages were bumped.

We now have support for headers/cookies. The `ResourceContext` each route gets has headers/cookies property that is set based on the incoming request and now and both Data/View result supports setting cookies/headers on the various factory methods.

I think this is largely in parity of not beyond what the features V2 with the exception of file handling which was only partial included in V1.  File handling can wait for now. 

One minor thing that is missing is the 'printing' of routes when it generates them. I'm going to try to tackle that tonight. 

As noted in the post before this we do need to add back some of the `features` we had in the stack like MongoDB etc. That will be the next thing I start looking at that might can line up with features.

**Comment by lxndrdagreat** [comment]
I've been working on a project in the stack this weekend (still V1) and am really happy with it, but we definitely need to focus heavily on documentation after the V2 release. These things especially (though they might be different/gone in V2): middleware, @body, @local, @path.

**Comment by tommyphilyaw** [comment]
Once this is stable I want to have a conversation about documentation. 

We need a few levels of it I think:

- source code level of the foundation packages
- Proper project level docs either via a generated static site or wiki pages on the unthink-foundation package. This project houses the core comments and API used in the unithink-cli. So I want docs to leave there vs here for it that explain how it all works and semantics enforced. 
- docs in this project for any remaining concepts or built in things copied out when the cli inits a project. 

Would also like to see if can't get group of us tackling this once we define the formats for it.

**Comment by tommyphilyaw** [comment]
Added mongodb back to the stack and slightly different than V1

- The mongodb service is no longer class based
- No dependency injection is used

The interface now looks like this:

```
import { getClient, getDefaultDb, getDefaultCollection } from '

```

**Comment by tommyphilyaw** [comment]
@lxndrdagreat [here](https://github.com/epandco/unthink-cli/blob/2d31db402e8039c2d7305e16b75c47c9b7dad3f5/unthink-stack/docs/unthink-foundation.md) is what I have so far for docs on the unthink-foundation.

I ended up putting it in a `docs` folder and separating it out of the README.md because it's going to be fairly long. 

Open to changing that. I just didn't want to load that README down with this.

**Pull request merged**
